<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'vortextangent\\epeiros\\dbunitarraydataset' => '/helpers/databaseTesting/DbUnitArrayDataSet.php',
                'vortextangent\\epeiros\\gettertestgenerator' => '/generators/GetterTestGenerator.php',
                'vortextangent\\epeiros\\http\\headertesthelper' => '/helpers/HeaderTestHelper.php',
                'vortextangent\\epeiros\\http\\setcookietesthelper' => '/helpers/SetCookieTestHelper.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
